import * as THREE from "./node_modules/three/build/three.module.js";

const K={acc:"after-space-account",set:"after-space-settings",lang:"after-space-language",world:"after-space-world"};
const CFG={r:180,load:32,step:8,sea:2,ph:1.8,pr:0.34,walk:6.3,sprint:9,jump:8.5,g:24,reach:7,mine:1,day:240,hp:300,save:6};
const $=s=>document.querySelector(s),dom={canvas:$("#game-canvas"),menu:$("#menu-screen"),reg:$("#register-panel"),acc:$("#account-panel"),set:$("#settings-panel"),form:$("#register-form"),user:$("#username"),pass:$("#password"),accName:$("#account-name"),play:$("#play-button"),setBtn:$("#settings-button"),setClose:$("#close-settings"),logout:$("#logout-button"),worldBtns:[...document.querySelectorAll(".world-btn")],music:$("#music-enabled"),vol:$("#music-volume"),third:$("#third-person-toggle"),msg:$("#menu-message"),hud:$("#hud"),player:$("#player-name"),world:$("#world-name"),time:$("#time-label"),status:$("#status-label"),hp:$("#health-fill"),en:$("#energy-fill"),threat:$("#threat-fill"),ret:$("#reticle"),bar:$("#build-bar"),grid:$("#build-menu-grid"),sword:$("#sword-button"),items:$("#items-button"),panel:$("#all-items-panel"),all:$("#all-items-grid"),close:$("#close-items")};
const txt={zh:{welcome:"歡迎來到 AFTER SPACE",subtitle:"註冊帳號後，進入超大型方塊世界。白天採集、夜晚生存、自由建造，並用滑鼠與方向鍵操控整個世界。",f1:"超大型地圖",f1b:"世界採用近距離載入，保留大地圖感，同時避免一次渲染全部方塊造成卡頓。",f2:"建造與戰鬥",f2b:"左側建造選單、底部快捷欄、獨立劍按鈕與物品箱按鈕都保留下來。",f3:"帳號與世界",f3b:"帳號會被記住，多世界存檔獨立保存，除非你主動註銷才會清除帳號。",register:"帳號註冊",gate:"請先註冊帳號",username:"使用者名稱",password:"密碼",remember:"註冊並記住帳號",signed:"已登入帳號",enter:"進入世界",settings:"設定",logout:"註銷帳號",settingsTitle:"遊戲設定",music:"背景音樂",volume:"音量",third:"預設第三人稱",caps:"按下 Caps Lock 可切換繁體中文 / English。",player:"玩家",world:"世界",time:"時間",status:"狀態",controls:["方向鍵移動","Space 跳躍","Shift 衝刺","左鍵揮劍或挖掘","右鍵放置方塊","V 切換第一 / 第三人稱","I 開啟物品箱"],health:"生命值",energy:"體力",threat:"威脅",items:"物品箱",all:"全部物品",sword:"劍",calm:"安全",alert:"危險",ready:"準備完成",mining:"挖掘中",noBlocks:"這個建材沒有庫存",registered:"帳號已註冊並記住，不會自動登出。",deleted:"帳號已註銷。",invalid:"使用者名稱至少 3 字，密碼至少 4 字。",respawn:"你掉出地圖外，已重生。",world1:"第一世界",world2:"第二世界",world3:"第三世界",bag:"背包",activeSword:"劍已裝備",activeBuild:"建造模式",day:"第",daySuffix:"天"},en:{welcome:"Welcome To AFTER SPACE",subtitle:"Register your account, then enter a huge block world with gathering, survival, building, and night combat.",f1:"Huge Map",f1b:"The world streams around the player so it feels large without rendering everything at once.",f2:"Building And Combat",f2b:"The left build menu, bottom quick bar, sword button, and item box stay available.",f3:"Account And Worlds",f3b:"Your account stays remembered, and each world saves separately.",register:"Account Registration",gate:"Please Register First",username:"Username",password:"Password",remember:"Register And Remember",signed:"Signed In",enter:"Enter World",settings:"Settings",logout:"Delete Account",settingsTitle:"Game Settings",music:"Background Music",volume:"Volume",third:"Default Third Person",caps:"Press Caps Lock to switch Traditional Chinese / English.",player:"Player",world:"World",time:"Time",status:"Status",controls:["Arrow Keys Move","Space Jump","Shift Sprint","Left Click Sword Or Mine","Right Click Place Block","V Toggle First / Third Person","I Open Item Box"],health:"Health",energy:"Stamina",threat:"Threat",items:"Items",all:"All Items",sword:"Sword",calm:"Safe",alert:"Danger",ready:"Ready",mining:"Mining",noBlocks:"No stock for this block",registered:"Account saved and will stay signed in.",deleted:"Account deleted.",invalid:"Username must be 3+ and password 4+.",respawn:"You fell out of the map and respawned.",world1:"World One",world2:"World Two",world3:"World Three",bag:"Bag",activeSword:"Sword Equipped",activeBuild:"Build Mode",day:"Day",daySuffix:""}};
const items=[{id:"grass",zh:"草地",en:"Grass",c:0x6cbc57},{id:"dirt",zh:"泥土",en:"Dirt",c:0x7f5b36},{id:"stone",zh:"石頭",en:"Stone",c:0x8d95a3},{id:"sand",zh:"沙子",en:"Sand",c:0xd8c07c},{id:"wood",zh:"木頭",en:"Wood",c:0x96653d},{id:"leaves",zh:"樹葉",en:"Leaves",c:0x43984a},{id:"brick",zh:"紅磚",en:"Brick",c:0xa95d4b},{id:"glass",zh:"玻璃",en:"Glass",c:0xa8dcff,t:1,o:.72},{id:"metal",zh:"金屬",en:"Metal",c:0xaab2bf},{id:"ice",zh:"冰塊",en:"Ice",c:0xdff8ff,t:1,o:.84},{id:"neon",zh:"霓虹磚",en:"Neon",c:0x67f3ff,e:0x1c6a73},{id:"crystal",zh:"水晶",en:"Crystal",c:0x76e9ff,e:0x17384e},{id:"basalt",zh:"玄武岩",en:"Basalt",c:0x38414d},{id:"obsidian",zh:"黑曜石",en:"Obsidian",c:0x2f2448}];
const drops={slimeGel:{zh:"史萊姆膠",en:"Slime Gel"},shadowShard:{zh:"暗影碎片",en:"Shadow Shard"},woodCore:{zh:"木芯",en:"Wood Core"}};
const mobs=[{id:"slime",zh:"史萊姆",en:"Slime",c:0x7cff97,hp:4,s:1.6,d:8,drop:"slimeGel"},{id:"shade",zh:"暗影怪",en:"Shade",c:0x9d84ff,hp:5,s:2.2,d:12,drop:"shadowShard"},{id:"logger",zh:"林地怪",en:"Logger Beast",c:0xb59263,hp:6,s:1.8,d:10,drop:"woodCore"}];
const S={lang:localStorage.getItem(K.lang)||"zh",account:null,playing:false,worldId:"world-1",sel:0,sword:false,third:true,yaw:0,pitch:-.22,onGround:false,hp:CFG.hp,en:100,time:.24,day:1,mineKey:null,mineProg:0,left:false,save:0,spawn:0,chx:null,chz:null};
const P={pos:new THREE.Vector3(0,12,0),vel:new THREE.Vector3(),inv:{},chest:{}},Set={musicEnabled:true,volume:.18,thirdDefault:true},keys=new Set(),blocks=new Map(),blockMeshes=[],changes=new Map(),monsters=[];
const renderer=new THREE.WebGLRenderer({canvas:dom.canvas,antialias:false,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1));renderer.setSize(innerWidth,innerHeight);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9cccf3);scene.fog=new THREE.Fog(0x9cccf3,24,170);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.1,260),worldRoot=new THREE.Group(),mobRoot=new THREE.Group(),avatar=new THREE.Group();scene.add(worldRoot,mobRoot,avatar);
const hemi=new THREE.HemisphereLight(0xd4e9ff,0x203246,1.02),sun=new THREE.DirectionalLight(0xffefc2,1.45),moon=new THREE.PointLight(0x8bd0ff,6,240,2);scene.add(hemi,sun,moon);
const water=new THREE.Mesh(new THREE.PlaneGeometry(1600,1600),new THREE.MeshStandardMaterial({color:0x2d78aa,transparent:true,opacity:.56}));water.rotation.x=-Math.PI/2;water.position.y=CFG.sea-.08;scene.add(water);
const stars=(()=>{const g=new THREE.BufferGeometry(),p=new Float32Array(3600);for(let i=0;i<1200;i++){p[i*3]=(Math.random()-.5)*700;p[i*3+1]=60+Math.random()*160;p[i*3+2]=(Math.random()-.5)*700}g.setAttribute("position",new THREE.BufferAttribute(p,3));return new THREE.Points(g,new THREE.PointsMaterial({color:0xffffff,size:.8,transparent:true,opacity:.22}))})();scene.add(stars);
const clock=new THREE.Clock(),raycaster=new THREE.Raycaster(),box=new THREE.BoxGeometry(1,1,1),mobBox=new THREE.BoxGeometry(1,1,1),fwd=new THREE.Vector3(),right=new THREE.Vector3(),up=new THREE.Vector3(0,1,0);
const mats=new Map(items.map(i=>[i.id,new THREE.MeshStandardMaterial({color:i.c,emissive:i.e||0,roughness:.9,metalness:i.id==="metal"?.45:.06,transparent:!!i.t,opacity:i.o??1})]));
const mobMats=new Map(mobs.map(m=>[m.id,new THREE.MeshStandardMaterial({color:m.c,roughness:.72,emissive:0x151522})]));
let audio=null,music=null;

const L=()=>txt[S.lang],nameOf=id=>items.find(i=>i.id===id)?.[S.lang]||drops[id]?.[S.lang]||id,wKey=()=>`${K.world}:${S.account.username}:${S.worldId}`,bKey=(x,y,z)=>`${x},${y},${z}`;
const hAt=(x,z)=>Math.round((9+Math.sin(x*.06)*5+Math.cos(z*.08)*4+Math.sin((x+z)*.025)*6)/2)*2;
const biome=(x,z)=>{const n=Math.sin(x*.024)+Math.cos(z*.025)+Math.sin((x-z)*.016);if(n<-.9)return"sand";if(n>1.1)return"ice";if(n>.35)return"crystal";return"grass"};
function deco(x,z,t){const s=Math.abs(Math.sin(x*13.23+z*6.17)),a=[],b=biome(x,z);if(b==="grass"&&s>.985){a.push([x,t+1,z,"wood"],[x,t+2,z,"wood"],[x,t+3,z,"wood"]);for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++)a.push([x+dx,t+4,z+dz,"leaves"])}if(b==="crystal"&&s>.988)a.push([x,t+1,z,"crystal"],[x,t+2,z,"neon"]);return a}
function baseAt(x,y,z){if(Math.abs(x)>CFG.r||Math.abs(z)>CFG.r)return null;const t=hAt(x,z),b=biome(x,z),top=b==="sand"?"sand":b==="ice"?"ice":b==="crystal"?"basalt":"grass",low=b==="sand"?"sand":b==="crystal"?"basalt":"dirt";if(y===t)return top;if(y===t-1)return low;if(y===t-2)return b==="crystal"?"obsidian":"stone";return deco(x,z,t).find(v=>v[0]===x&&v[1]===y&&v[2]===z)?.[3]||null}
const getId=(x,y,z)=>changes.has(bKey(x,y,z))?changes.get(bKey(x,y,z)):baseAt(x,y,z);
function clearWorld(){[...blocks.values()].forEach(m=>worldRoot.remove(m));blocks.clear();blockMeshes.length=0}
function addBlockMesh(x,y,z,id){const m=new THREE.Mesh(box,mats.get(id));m.position.set(x,y,z);m.userData={x,y,z,id};worldRoot.add(m);blocks.set(bKey(x,y,z),m);blockMeshes.push(m)}
function rebuild(force=false){const cx=Math.floor(P.pos.x/CFG.step),cz=Math.floor(P.pos.z/CFG.step);if(!force&&cx===S.chx&&cz===S.chz)return;S.chx=cx;S.chz=cz;clearWorld();const px=cx*CFG.step,pz=cz*CFG.step;for(let x=px-CFG.load;x<=px+CFG.load;x++)for(let z=pz-CFG.load;z<=pz+CFG.load;z++){const t=hAt(x,z);for(let y=t-2;y<=t+4;y++){const id=getId(x,y,z);if(id)addBlockMesh(x,y,z,id)}}}
function setChange(x,y,z,id){const k=bKey(x,y,z),base=baseAt(x,y,z);if(id===base||(id===null&&base===null))changes.delete(k);else changes.set(k,id)}
function sync(x,y,z){const k=bKey(x,y,z),e=blocks.get(k),n=getId(x,y,z);if(e&&!n){worldRoot.remove(e);blocks.delete(k);const i=blockMeshes.indexOf(e);if(i>=0)blockMeshes.splice(i,1);return}if(!e&&n){addBlockMesh(x,y,z,n);return}if(e&&n&&e.userData.id!==n){e.material=mats.get(n);e.userData.id=n}}
function ensureInv(){items.forEach(i=>{if(!(i.id in P.inv))P.inv[i.id]=80});Object.keys(drops).forEach(i=>{if(!(i in P.inv))P.inv[i]=0})}
function resetData(){P.inv={};P.chest={};ensureInv();Object.keys(P.inv).forEach(k=>P.chest[k]=P.inv[k]);S.hp=CFG.hp;S.en=100;S.time=.24;S.day=1}
function ground(x,z){const rx=Math.round(x),rz=Math.round(z);for(let y=30;y>=-8;y--)if(getId(rx,y,rz))return y+.5;return CFG.sea}
function spawn(){P.pos.set(0,ground(0,0)+CFG.ph,0);P.vel.set(0,0,0)}
function save(reason=""){if(!S.account)return;localStorage.setItem(wKey(),JSON.stringify({player:{x:P.pos.x,y:P.pos.y,z:P.pos.z},inventory:P.inv,chest:P.chest,hp:S.hp,en:S.en,time:S.time,day:S.day,changes:[...changes.entries()]}));if(reason)dom.ret.textContent=reason}
function loadWorld(){changes.clear();monsters.splice(0).forEach(m=>mobRoot.remove(m.mesh));resetData();spawn();const raw=localStorage.getItem(wKey());if(raw)try{const s=JSON.parse(raw);P.inv=s.inventory||P.inv;P.chest=s.chest||P.chest;S.hp=s.hp??CFG.hp;S.en=s.en??100;S.time=s.time??.24;S.day=s.day??1;if(s.player)P.pos.set(s.player.x,s.player.y,s.player.z);if(Array.isArray(s.changes))s.changes.forEach(([k,v])=>changes.set(k,v))}catch{}rebuild(true)}
function loadSet(){const raw=localStorage.getItem(K.set);if(raw)try{Object.assign(Set,JSON.parse(raw))}catch{}dom.music.checked=Set.musicEnabled;dom.vol.value=String(Math.round(Set.volume*100));dom.third.checked=Set.thirdDefault;S.third=Set.thirdDefault}
const saveSet=()=>localStorage.setItem(K.set,JSON.stringify(Set)),msg=t=>dom.msg.textContent=t;
function setAccUI(){if(S.account){dom.reg.classList.add("hidden");dom.acc.classList.remove("hidden");dom.accName.textContent=S.account.username;dom.player.textContent=S.account.username}else{dom.reg.classList.remove("hidden");dom.acc.classList.add("hidden");dom.player.textContent="Explorer"}}
function loadAcc(){const raw=localStorage.getItem(K.acc);if(raw)try{S.account=JSON.parse(raw)}catch{localStorage.removeItem(K.acc)}}
function saveAcc(u,p){S.account={username:u,password:p};localStorage.setItem(K.acc,JSON.stringify(S.account));setAccUI();msg(L().registered)}
function delAcc(){localStorage.removeItem(K.acc);S.account=null;setAccUI();msg(L().deleted)}
function applyLang(){const t=L();document.documentElement.lang=S.lang==="zh"?"zh-Hant":"en";$("#main-title").textContent=t.welcome;$("#main-subtitle").textContent=t.subtitle;$("#feature-1-title").textContent=t.f1;$("#feature-1-body").textContent=t.f1b;$("#feature-2-title").textContent=t.f2;$("#feature-2-body").textContent=t.f2b;$("#feature-3-title").textContent=t.f3;$("#feature-3-body").textContent=t.f3b;$("#register-label").textContent=t.register;$("#register-title").textContent=t.gate;$("#username-label").textContent=t.username;$("#password-label").textContent=t.password;$("#register-button").textContent=t.remember;$("#signed-in-label").textContent=t.signed;dom.play.textContent=t.enter;dom.setBtn.textContent=t.settings;dom.logout.textContent=t.logout;$("#settings-label").textContent=t.settings;$("#settings-title").textContent=t.settingsTitle;$("#music-label").textContent=t.music;$("#volume-label").textContent=t.volume;$("#camera-label").textContent=t.third;$("#caps-note").textContent=t.caps;$("#player-label").textContent=t.player;$("#world-label").textContent=t.world;$("#time-label-text").textContent=t.time;$("#status-label-text").textContent=t.status;$("#health-text").textContent=t.health;$("#energy-text").textContent=t.energy;$("#threat-text").textContent=t.threat;$("#build-menu-label").textContent=t.items;$("#build-menu-title").textContent=t.all;$("#all-items-label").textContent=t.items;$("#all-items-title").textContent=t.all;dom.sword.textContent=t.sword;dom.items.textContent=t.items;document.querySelectorAll(".controls p").forEach((p,i)=>p.textContent=t.controls[i]||"");dom.worldBtns[0].textContent=t.world1;dom.worldBtns[1].textContent=t.world2;dom.worldBtns[2].textContent=t.world3;barUI();gridUI();allUI();hud()}
function startMusic(){if(!Set.musicEnabled)return;if(!audio)audio=new AudioContext();if(music)return;const gain=audio.createGain(),filter=audio.createBiquadFilter(),a=audio.createOscillator(),b=audio.createOscillator(),c=audio.createOscillator();gain.gain.value=Set.volume*.03;filter.type="lowpass";filter.frequency.value=850;filter.Q.value=.2;a.type="sine";b.type="sine";c.type="triangle";a.frequency.value=174.61;b.frequency.value=220;c.frequency.value=261.63;a.connect(filter);b.connect(filter);c.connect(filter);filter.connect(gain);gain.connect(audio.destination);a.start();b.start();c.start();music={gain,a,b,c}}
function audioUI(){if(!Set.musicEnabled&&music){music.a.stop();music.b.stop();music.c.stop();music=null;return}if(Set.musicEnabled){startMusic();if(music)music.gain.gain.value=Set.volume*.03}}
function damageSound(){if(!audio)audio=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.type="square";o.frequency.setValueAtTime(240,audio.currentTime);o.frequency.exponentialRampToValueAtTime(120,audio.currentTime+.15);g.gain.setValueAtTime(.001,audio.currentTime);g.gain.exponentialRampToValueAtTime(Math.max(.02,Set.volume*.12),audio.currentTime+.02);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.2)}
function avatarUI(){avatar.clear();const b=new THREE.Mesh(new THREE.BoxGeometry(.8,1,.42),new THREE.MeshStandardMaterial({color:0x6fc6ff,roughness:.72})),h=new THREE.Mesh(new THREE.BoxGeometry(.56,.56,.56),new THREE.MeshStandardMaterial({color:0xf4d4bd,roughness:.84})),l=new THREE.Mesh(new THREE.BoxGeometry(.28,.88,.28),new THREE.MeshStandardMaterial({color:0x223755,roughness:.86})),r=l.clone();b.position.y=1.05;h.position.y=1.86;l.position.set(-.18,.42,0);r.position.set(.18,.42,0);avatar.add(b,h,l,r)}
function barUI(){dom.bar.innerHTML="";items.forEach((it,i)=>{const b=document.createElement("button");b.className=`build-slot${i===S.sel?" active":""}`;b.innerHTML=`<strong>${it[S.lang]}</strong><span>${L().bag}: ${P.inv[it.id]||0}</span><em>${i+1}</em>`;b.addEventListener("click",()=>{S.sel=i;S.sword=false;barUI();gridUI();actions();dom.ret.textContent=it[S.lang]});dom.bar.append(b)})}
function gridUI(){dom.grid.innerHTML="";items.forEach((it,i)=>{const b=document.createElement("button");b.className=`item-card${i===S.sel?" active":""}`;b.innerHTML=`<strong>${it[S.lang]}</strong><span>${L().bag}: ${P.inv[it.id]||0}</span>`;b.addEventListener("click",()=>{S.sel=i;S.sword=false;barUI();gridUI();actions();dom.ret.textContent=it[S.lang]});dom.grid.append(b)})}
function allUI(){dom.all.innerHTML="";[...items.map(i=>i.id),...Object.keys(drops)].forEach(id=>{const c=document.createElement("article");c.className="item-card";c.innerHTML=`<strong>${nameOf(id)}</strong><span>${L().bag}: ${P.inv[id]||0}</span>`;dom.all.append(c)})}
function actions(){dom.sword.classList.toggle("active",S.sword);dom.items.classList.toggle("active",!dom.panel.classList.contains("hidden"))}
const night=()=>THREE.MathUtils.clamp((Math.cos(S.time*Math.PI*2)+.25)*.8,0,1);
function hud(){dom.player.textContent=S.account?.username||"Explorer";dom.world.textContent=L()[S.worldId.replace("-","")];const m=Math.floor(S.time*24*60),hh=String(Math.floor(m/60)%24).padStart(2,"0"),mm=String(m%60).padStart(2,"0");dom.time.textContent=S.lang==="zh"?`${L().day} ${S.day} ${L().daySuffix} ${hh}:${mm}`:`${L().day} ${S.day} ${hh}:${mm}`;dom.status.textContent=monsters.length?L().alert:L().calm;dom.hp.style.width=`${S.hp/CFG.hp*100}%`;dom.en.style.width=`${S.en}%`;dom.threat.style.width=`${Math.min(100,monsters.length*18+night()*60)}%`}
function sky(){const a=S.time*Math.PI*2,d=THREE.MathUtils.clamp(Math.sin(a)*.72+.4,.08,1),n=1-d,dc=new THREE.Color(0x9cccf3),nc=new THREE.Color(0x1f3257);scene.background.copy(nc.clone().lerp(dc,d));scene.fog.color.copy(scene.background);stars.material.opacity=.08+n*.82;hemi.intensity=.24+d*1.02;sun.intensity=.1+d*1.55;sun.position.set(Math.cos(a)*50,Math.max(7,Math.sin(a)*42),Math.sin(a)*30);moon.position.set(-sun.position.x*.75,18+n*16,-sun.position.z);moon.intensity=4+n*15}
function targetBlock(){raycaster.setFromCamera(new THREE.Vector2(0,0),camera);return raycaster.intersectObjects(blockMeshes,false).find(h=>h.distance<=CFG.reach)||null}
function targetMob(){raycaster.setFromCamera(new THREE.Vector2(0,0),camera);const hits=raycaster.intersectObjects(monsters.map(m=>m.mesh),false);return!hits.length||hits[0].distance>CFG.reach?null:monsters.find(m=>m.mesh===hits[0].object)||null}
function spawnMob(){if(monsters.length>=10||night()<.35)return;const d=mobs[Math.floor(Math.random()*mobs.length)],a=Math.random()*Math.PI*2,dist=15+Math.random()*14,x=P.pos.x+Math.cos(a)*dist,z=P.pos.z+Math.sin(a)*dist;if(Math.abs(x)>CFG.r-2||Math.abs(z)>CFG.r-2)return;const mesh=new THREE.Mesh(mobBox,mobMats.get(d.id));mesh.scale.set(d.id==="logger"?1.2:.95,d.id==="shade"?1.2:.95,d.id==="logger"?1.4:.95);mesh.position.set(x,ground(x,z)+.8,z);mobRoot.add(mesh);monsters.push({def:d,mesh,hp:d.hp,cd:0,bob:Math.random()*Math.PI*2})}
function mobsTick(dt){S.spawn-=dt;if(S.spawn<=0){spawnMob();S.spawn=2.8}monsters.forEach(m=>{m.cd=Math.max(0,m.cd-dt);m.bob+=dt*3.2;const to=P.pos.clone().sub(m.mesh.position),flat=new THREE.Vector3(to.x,0,to.z),dist=flat.length();if(dist>1.1){flat.normalize();m.mesh.position.addScaledVector(flat,m.def.s*dt)}m.mesh.position.y=ground(m.mesh.position.x,m.mesh.position.z)+.75+Math.sin(m.bob)*.04;if(dist<1.7&&m.cd===0){S.hp=Math.max(0,S.hp-m.def.d);m.cd=1.1;damageSound()}});for(let i=monsters.length-1;i>=0;i--)if(monsters[i].hp<=0||monsters[i].mesh.position.distanceTo(P.pos)>85){if(monsters[i].hp<=0){const d=monsters[i].def.drop;P.inv[d]=(P.inv[d]||0)+1;P.chest[d]=P.inv[d]}mobRoot.remove(monsters[i].mesh);monsters.splice(i,1)}allUI()}
function collide(x,y,z){const minX=Math.floor(x-CFG.pr),maxX=Math.floor(x+CFG.pr),minZ=Math.floor(z-CFG.pr),maxZ=Math.floor(z+CFG.pr),minY=Math.floor(y-CFG.ph+.05),maxY=Math.floor(y-.15);for(let bx=minX;bx<=maxX;bx++)for(let by=minY;by<=maxY;by++)for(let bz=minZ;bz<=maxZ;bz++)if(getId(bx,by,bz))return true;return false}
function move(dt){const inp=new THREE.Vector3();if(keys.has("ArrowUp"))inp.z-=1;if(keys.has("ArrowDown"))inp.z+=1;if(keys.has("ArrowLeft"))inp.x-=1;if(keys.has("ArrowRight"))inp.x+=1;let sp=CFG.walk;if((keys.has("ShiftLeft")||keys.has("ShiftRight"))&&S.en>0){sp=CFG.sprint;S.en=Math.max(0,S.en-dt*9)}else S.en=Math.min(100,S.en+dt*4.5);if(inp.lengthSq()>0){inp.normalize();camera.getWorldDirection(fwd);fwd.y=0;fwd.normalize();if(fwd.lengthSq()<.001)fwd.set(Math.sin(S.yaw),0,Math.cos(S.yaw));right.crossVectors(fwd,up).normalize();const m=new THREE.Vector3();m.addScaledVector(fwd,-inp.z);m.addScaledVector(right,inp.x);m.normalize().multiplyScalar(sp*dt);const nx=P.pos.x+m.x,nz=P.pos.z+m.z;if(!collide(nx,P.pos.y,P.pos.z))P.pos.x=nx;if(!collide(P.pos.x,P.pos.y,nz))P.pos.z=nz}P.vel.y-=CFG.g*dt;const ny=P.pos.y+P.vel.y*dt;if(!collide(P.pos.x,ny,P.pos.z)){P.pos.y=ny;S.onGround=false}else{if(P.vel.y<0)S.onGround=true;P.vel.y=0}const floor=ground(P.pos.x,P.pos.z)+CFG.ph;if(P.pos.y<floor&&!collide(P.pos.x,floor,P.pos.z)){P.pos.y=floor;P.vel.y=0;S.onGround=true}if(P.pos.y<-50){spawn();dom.ret.textContent=L().respawn}}
function avatarTick(){avatar.position.set(P.pos.x,P.pos.y-CFG.ph,P.pos.z);avatar.rotation.y=S.yaw;avatar.visible=S.third;const w=keys.has("ArrowUp")||keys.has("ArrowDown")||keys.has("ArrowLeft")||keys.has("ArrowRight"),s=w?Math.sin(clock.elapsedTime*8)*.18:0;if(avatar.children[2])avatar.children[2].rotation.x=s;if(avatar.children[3])avatar.children[3].rotation.x=-s}
function cam(){camera.rotation.order="YXZ";camera.rotation.y=S.yaw;camera.rotation.x=S.pitch;if(S.third){const head=P.pos.clone().add(new THREE.Vector3(0,1.2,0)),want=P.pos.clone().add(new THREE.Vector3(0,2.2,5.8).applyEuler(new THREE.Euler(S.pitch*.24,S.yaw,0,"YXZ"))),dir=want.clone().sub(head).normalize(),dist=head.distanceTo(want);raycaster.set(head,dir);const hit=raycaster.intersectObjects(blockMeshes,false),fin=hit.length&&hit[0].distance<dist?hit[0].point.clone().add(dir.clone().multiplyScalar(-.45)):want;camera.position.lerp(fin,.18);camera.lookAt(P.pos.x,P.pos.y+1.2,P.pos.z)}else camera.position.copy(P.pos).add(new THREE.Vector3(0,.16,0))}
function attack(){const m=targetMob();if(!m)return false;m.hp-=3;dom.ret.textContent=`${L().sword} ${m.def[S.lang]}`;return true}
function mine(dt){const hit=targetBlock();if(!hit){S.mineKey=null;S.mineProg=0;return}const k=bKey(hit.object.userData.x,hit.object.userData.y,hit.object.userData.z);if(S.mineKey!==k){S.mineKey=k;S.mineProg=0}S.mineProg+=dt;dom.ret.textContent=`${L().mining} ${Math.min(100,Math.floor(S.mineProg/CFG.mine*100))}%`;if(S.mineProg>=CFG.mine){const{x,y,z,id}=hit.object.userData;setChange(x,y,z,null);sync(x,y,z);P.inv[id]=(P.inv[id]||0)+1;P.chest[id]=P.inv[id];barUI();gridUI();allUI();S.mineKey=null;S.mineProg=0}}
function place(){const cur=items[S.sel];if((P.inv[cur.id]||0)<=0){dom.ret.textContent=L().noBlocks;return}const hit=targetBlock();if(!hit)return;const pos=hit.object.position.clone().add(hit.face.normal),x=Math.round(pos.x),y=Math.round(pos.y),z=Math.round(pos.z);if(new THREE.Vector3(x,y,z).distanceTo(P.pos)<1.8||getId(x,y,z))return;setChange(x,y,z,cur.id);sync(x,y,z);P.inv[cur.id]-=1;P.chest[cur.id]=P.inv[cur.id];barUI();gridUI();allUI()}
function actionState(){actions();dom.ret.textContent=S.sword?L().activeSword:L().activeBuild}
function start(){loadWorld();S.third=Set.thirdDefault;dom.menu.classList.add("hidden");dom.hud.classList.remove("hidden");S.playing=true;barUI();gridUI();allUI();actionState();hud();sky();cam();audioUI();dom.canvas.requestPointerLock()}
function onReg(e){e.preventDefault();const u=dom.user.value.trim(),p=dom.pass.value.trim();if(u.length<3||p.length<4){msg(L().invalid);return}saveAcc(u,p)}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);if(S.playing){S.time+=dt/CFG.day;if(S.time>=1){S.time-=1;S.day+=1}S.save+=dt;move(dt);rebuild();mobsTick(dt);sky();avatarTick();cam();hud();if(S.left){if(S.sword)attack();else mine(dt)}else if(!S.sword){const hit=targetBlock();dom.ret.textContent=hit?nameOf(hit.object.userData.id):L().ready}else dom.ret.textContent=L().activeSword;if(S.save>=CFG.save){save();S.save=0}if(S.hp<=0){S.hp=CFG.hp;spawn()}}renderer.render(scene,camera)}

loadAcc();loadSet();setAccUI();ensureInv();applyLang();avatarUI();spawn();rebuild(true);barUI();gridUI();allUI();actions();hud();sky();cam();
dom.form.addEventListener("submit",onReg);dom.play.addEventListener("click",()=>S.account&&start());dom.setBtn.addEventListener("click",()=>dom.set.classList.toggle("hidden"));dom.setClose.addEventListener("click",()=>dom.set.classList.add("hidden"));dom.logout.addEventListener("click",delAcc);
dom.worldBtns.forEach(b=>b.addEventListener("click",()=>{dom.worldBtns.forEach(v=>v.classList.remove("active"));b.classList.add("active");S.worldId=b.dataset.world;hud()}));
dom.sword.addEventListener("click",()=>{S.sword=!S.sword;actionState()});dom.items.addEventListener("click",()=>{dom.panel.classList.toggle("hidden");actions()});dom.close.addEventListener("click",()=>{dom.panel.classList.add("hidden");actions()});
dom.music.addEventListener("change",()=>{Set.musicEnabled=dom.music.checked;saveSet();audioUI()});dom.vol.addEventListener("input",()=>{Set.volume=Number(dom.vol.value)/100;saveSet();audioUI()});dom.third.addEventListener("change",()=>{Set.thirdDefault=dom.third.checked;S.third=Set.thirdDefault;saveSet()});
addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
document.addEventListener("mousemove",e=>{if(document.pointerLockElement!==dom.canvas||!S.playing)return;S.yaw-=e.movementX*.0022;S.pitch-=e.movementY*.002;S.pitch=THREE.MathUtils.clamp(S.pitch,-1.25,1.15)});
document.addEventListener("keydown",e=>{if(e.code==="CapsLock"){S.lang=S.lang==="zh"?"en":"zh";localStorage.setItem(K.lang,S.lang);applyLang();return}if(e.code==="KeyV"&&S.playing){S.third=!S.third;return}if(e.code==="KeyI"&&S.playing){dom.panel.classList.toggle("hidden");actions();return}keys.add(e.code);if(e.code==="Space"&&S.onGround)P.vel.y=CFG.jump;if(e.code.startsWith("Digit")){const n=Number(e.code.replace("Digit",""))-1;if(n>=0&&n<items.length){S.sel=n;S.sword=false;barUI();gridUI();actions()}}});
document.addEventListener("keyup",e=>keys.delete(e.code));
addEventListener("mousedown",e=>{if(!S.playing)return;if(document.pointerLockElement!==dom.canvas){dom.canvas.requestPointerLock();audioUI();return}audioUI();if(e.button===0)S.left=true;if(e.button===2&&!S.sword)place()});
addEventListener("mouseup",e=>{if(e.button===0){S.left=false;S.mineKey=null;S.mineProg=0}});
addEventListener("contextmenu",e=>e.preventDefault());addEventListener("beforeunload",()=>save());loop();
